on:
  workflow_dispatch:
  schedule:
    - cron: '00 14 * * *'

  push:
    paths:
      # Triggers only when relevant files are updated
      - 'scrape.py'
      - '.github/workflows/scrape-and-save.yml'
    branches:
      - master
    tags-ignore:
      - '**' # prevent duplicate builds for any push of release tags

name: Scrape and save data

permissions:
  contents: write

jobs:
  # Attempt to build and store the result as GitHub Action artifact
  scrape:
    name: Scrape latest mark six data from HKJC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14" # 配合 Pipfile 的設定

      - name: Install dependencies and Playwright Browsers
        run: |
          pip install pipenv
          pipenv install --skip-lock
          # 我們在腳本中寫死了 channel="msedge"，所以要把它安裝到 Ubuntu 伺服器上
          pipenv run playwright install msedge --with-deps

      - name: Fetch and save response from HKJC API
        run: pipenv run python scrape.py
        
      - name: Commit files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: new updates fetched on $(date +"%Y-%m-%dT%H:%M:%S%z")" || :
          git push
